/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fakeTokens from "./FakeTokens";
export type { fakeTokens };
import type * as multiCoinBalanceLookupSol from "./MultiCoinBalanceLookup.sol";
export type { multiCoinBalanceLookupSol };
