/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FakeTokenA } from "./FakeTokenA";
export type { FakeTokenB } from "./FakeTokenB";
export type { MultiCoinBalanceLookup } from "./MultiCoinBalanceLookup";
