/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fakeTokenTemplateSol from "./FakeTokenTemplate.sol";
export type { fakeTokenTemplateSol };
export type { FakeTokenA } from "./FakeTokenA";
export type { FakeTokenB } from "./FakeTokenB";
export type { FakeTokenC } from "./FakeTokenC";
export type { FakeTokenD } from "./FakeTokenD";
export type { FakeTokenE } from "./FakeTokenE";
export type { FakeTokenF } from "./FakeTokenF";
export type { FakeTokenG } from "./FakeTokenG";
export type { FakeTokenH } from "./FakeTokenH";
export type { FakeTokenI } from "./FakeTokenI";
export type { FakeTokenJ } from "./FakeTokenJ";
export type { FakeTokenK } from "./FakeTokenK";
export type { FakeTokenL } from "./FakeTokenL";
export type { FakeTokenM } from "./FakeTokenM";
export type { FakeTokenN } from "./FakeTokenN";
export type { FakeTokenO } from "./FakeTokenO";
export type { FakeTokenP } from "./FakeTokenP";
export type { FakeTokenQ } from "./FakeTokenQ";
export type { FakeTokenR } from "./FakeTokenR";
export type { FakeTokenS } from "./FakeTokenS";
export type { FakeTokenT } from "./FakeTokenT";
export type { FakeTokenU } from "./FakeTokenU";
export type { FakeTokenV } from "./FakeTokenV";
export type { FakeTokenW } from "./FakeTokenW";
export type { FakeTokenX } from "./FakeTokenX";
export type { FakeTokenY } from "./FakeTokenY";
export type { FakeTokenZ } from "./FakeTokenZ";
