/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as fakeTokens from "./FakeTokens";
export * as multiCoinBalanceLookupSol from "./MultiCoinBalanceLookup.sol";
