/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "FakeTokenA",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FakeTokenA__factory>;
    getContractFactory(
      name: "FakeTokenB",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FakeTokenB__factory>;
    getContractFactory(
      name: "MultiCoinBalanceLookup",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MultiCoinBalanceLookup__factory>;

    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "FakeTokenA",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FakeTokenA>;
    getContractAt(
      name: "FakeTokenB",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FakeTokenB>;
    getContractAt(
      name: "MultiCoinBalanceLookup",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MultiCoinBalanceLookup>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
